"""Delta-base planning from differentiable flowsheets.

Refinery and value-chain planning has been done for decades with linear
programs whose unit submodels are *base plus delta vectors* — a first-order
Taylor expansion ``y ~= y0 + J (u - u0)``.  Aspen PIMS, Haverly GRTMPS,
Honeywell RPMS and AVEVA Spiral Plan all work this way; the refereed anchor is
Baker and Lasdon, "Successive Linear Programming at Exxon", Management Science
31(3), 1985.

In every one of those systems the delta vectors are generated by perturbing a
rigorous simulator one variable at a time, which is ``O(n)`` in the number of
decisions and is why they are refreshed on the order of annually.

difflow makes it ``O(1)``.  A flowsheet is a pure function with its flash,
recycle and unit solves embedded, so ``jax.jacobian`` returns the *reduced*
input-output sensitivity directly, already implicitly differentiated through
those inner solves.  That reduced Jacobian **is** the delta vector.  The
gradient costs a small constant multiple of one model evaluation whatever
``n`` is, while central differences cost exactly ``2n`` — so the advantage
grows linearly, and planning (horizon x units x decisions) is precisely where
``n`` gets large.  :mod:`difflow.planning.benchmark` measures it.

Quick start
-----------
::

    from difflow.planning import Block, Network, DeltaBasePlanner

    ngl = Block(name="ngl", fn=ngl_outputs,
                u_names=["ethane_recovery", "T_coldbox", "split"],
                y_names=["NGL_C2", "residue_F", "T_colfeed"],
                lb=[0.0, 180.0, 0.0], ub=[0.99, 240.0, 1.0])
    pwr = Block(name="power", fn=power_outputs,
                u_names=["fuel_F", "alloc"], y_names=["Power", "CO2"],
                lb=[0.0, 0.0], ub=[100.0, 1.0])

    net = Network([ngl, pwr], links=[("ngl.residue_F", "power.fuel_F")])

    planner = DeltaBasePlanner(
        net,
        prices={"ngl.NGL_C2": 12.0, "power.Power": 40.0},
        specs=[("ngl.T_colfeed", "<=", 213.0)],
        radius=0.3)

    res = planner.solve()
    res.plan                          # optimal decisions
    res.delta_vectors                 # the J blocks actually used
    res.pyomo_model                   # the emitted Pyomo model
    res.plan_sensitivity(wrt="prices")

What this module guarantees
---------------------------
Four traps produced wrong answers when this was prototyped by hand, and each
is encoded rather than left to the caller:

1. **The trust region is judged against your own model.**  Every LP proposal
   is evaluated with the *nonlinear* blocks and accepted only on realised
   improvement.  Without that, repeated re-linearisation walks far outside
   where any Taylor model is valid and the LP confidently returns garbage.
   The convergence theory is Eason and Biegler, "A trust region filter method
   for glass box/black box optimization", AIChE J 62(9), 2016
   (doi:10.1002/aic.15325); their first-order consistency requirement is
   satisfied *exactly* by an AD Taylor model, which is why this loop can claim
   convergence where the "recursion" heuristic cannot.
2. **True constraint violation is charged, not predicted violation.**  Elastic
   spec slacks keep the LP feasible, but scoring reads the nonlinear model.
   Score against the LP's own prediction and a planner with stale coefficients
   wins by running off-spec on paper.
3. **Bang-bang levers are vertex-seeded.**  A lever that sits at a bound and
   switches discretely with prices is not found reliably from a single
   interior start.
4. **The AD mode follows the shape.**  ``jacrev`` when outputs are fewer than
   inputs, ``jacfwd`` otherwise — never hard-coded.

A fifth diagnostic is surfaced rather than silently tolerated: a linearisation
that straddles a phase appearance or disappearance is *meaningless*, not
merely inaccurate, and blocks that declare a ``phase_fn`` raise
:class:`~difflow.planning.linearize.PhaseBoundaryWarning` when a proposal
crosses one.

Beyond the base plan
--------------------
* :mod:`difflow.planning.modifiers` — zeroth- and first-order plant-model
  corrections.  Value corrections alone converge to the *model's* optimum
  under structural mismatch; gradient corrections fix it (Marchetti, Chachuat
  and Bonvin, I&ECR 48(13), 2009, doi:10.1021/ie801352x).  In a delta-base LP
  the delta vectors *are* those gradients.
* :mod:`difflow.planning.backoff` — propagate a reconciled state's covariance
  through ``J`` to get uncertainty on the LP coefficients, and hence a
  principled constraint back-off.  Stale parameters cost feasibility more
  often than optimality.
* :mod:`difflow.planning.piecewise` — ``vmap`` a block over many operating
  points in one batched call and emit an SOS2 MILP.
* :mod:`difflow.planning.sensitivity` — the sensitivity of the *plan itself*:
  ``d(plan)/d(price)``, ``d(plan)/d(parameter)``, ``d(profit*)/d(parameter)``.
  This is what k_aug and sIPOPT give for a single NLP, and it is what makes
  capital planning tractable without scenario enumeration.  A commercial
  planning system structurally cannot provide it, because its submodels are
  not differentiable.

Explicit non-goals
------------------
This is not, and does not try to become, a commercial planning system.  Out of
scope: crude assay libraries, unit submodel libraries, empirical blending
correlations (octane, RVP, cloud point), scheduling, multi-site transport,
reporting and audit trails.  Those are the real moat of a product like PIMS;
they are not derivable from a flowsheet, and pretending otherwise would make
this module worse.

Also out of scope: **pooling and blending nonconvexity**.  Bilinear terms —
a stream quality multiplied by a stream flow — stay nonconvex no matter how
good the unit linearisation is (Haverly, ACM SIGMAP Bulletin 25, 1978).  That
needs global optimisation, not better delta vectors.  The pricing here is
linear in the block outputs, which is what keeps the model an LP; put a
bilinear pooling term in and the guarantees in this module no longer apply.

Finally, this module emits a Pyomo model rather than owning a solver, so it
composes with the existing Pyomo/IDAES ecosystem instead of competing with it.

Note:
    ``difflow.planning`` is a module alongside :mod:`difflow.eo_solver`,
    :mod:`difflow.estimation` and :mod:`difflow.uncertainty` — not a
    ``difflow.plugins`` entry point.  That registry is for unit operations.
"""

from difflow.planning.assemble import build_lp, trust_region_bounds
from difflow.planning.backoff import (
    BackOffResult, apply_backoff, constraint_backoff,
)
from difflow.planning.benchmark import (
    CostRatio, central_difference_gradient, format_scaling_table,
    gradient_cost_ratio, paired_time, planner_objective, scaling_study,
    time_callable,
)
from difflow.planning.block import Block
from difflow.planning.linearize import (
    Linearization, PhaseBoundaryWarning, check_delta_vectors,
    check_phase_transition, choose_ad_mode, classify_phase, jacobian_fn,
    linearize_block,
)
from difflow.planning.lp import LPModel, LPSolution, Spec, as_spec
from difflow.planning.modifiers import (
    ModifierAdaptationResult, Modifiers, run_modifier_adaptation,
    update_modifiers,
)
from difflow.planning.network import Link, Network, NetworkState
from difflow.planning.piecewise import (
    PiecewiseData, PiecewiseSpec, sample_piecewise,
)
from difflow.planning.planner import (
    DeltaBasePlanner, Iteration, PlanResult, TrustRegionOptions,
)
from difflow.planning.sensitivity import (
    PlanSensitivity, plan_sensitivity, price_switch_point,
)

__all__ = [
    # Core model
    "Block",
    "Network",
    "NetworkState",
    "Link",
    # Linearisation
    "Linearization",
    "linearize_block",
    "check_delta_vectors",
    "choose_ad_mode",
    "jacobian_fn",
    "classify_phase",
    "check_phase_transition",
    "PhaseBoundaryWarning",
    # LP
    "LPModel",
    "LPSolution",
    "Spec",
    "as_spec",
    "build_lp",
    "trust_region_bounds",
    # Planner
    "DeltaBasePlanner",
    "PlanResult",
    "TrustRegionOptions",
    "Iteration",
    # Sensitivity of the plan
    "PlanSensitivity",
    "plan_sensitivity",
    "price_switch_point",
    # Modifier adaptation
    "Modifiers",
    "update_modifiers",
    "run_modifier_adaptation",
    "ModifierAdaptationResult",
    # Back-off
    "constraint_backoff",
    "apply_backoff",
    "BackOffResult",
    # Piecewise / MILP
    "PiecewiseSpec",
    "PiecewiseData",
    "sample_piecewise",
    # Benchmarking
    "gradient_cost_ratio",
    "scaling_study",
    "format_scaling_table",
    "planner_objective",
    "central_difference_gradient",
    "time_callable",
    "paired_time",
    "CostRatio",
]
