"""Liquid density, viscosity and thermal conductivity, differentiable in JAX.

Every built-in species (``difflow.database.list_species()``) has one
correlation for each property. The coefficients come from published tables
(VDI Heat Atlas PPDS sets and Perry's 8th edition, as tabulated by the
`chemicals` package), from estimates built on data difflow already stores, or
for heavy water from a fit to CoolProp. They are generated by
``scripts/generate_liquid_properties.py`` into ``_liquid_property_data.py``;
neither `chemicals` nor CoolProp is needed at runtime. See issue #406 for how
the sources were chosen and how well each agrees with CoolProp.

Units: temperature K; density kg/m^3 (``liquid_density``) or mol/m^3
(``liquid_molar_density``); viscosity Pa s; thermal conductivity W/m/K.

Correlation forms (``LiquidCorrelation.form``):

- ``DIPPR105``: rho_molar = A / B^(1 + (1 - T/C)^D), mol/m^3.
- ``PPDS10``: rho_mass = rho_c + a tau^0.35 + b tau^(2/3) + c tau + d tau^(4/3),
  tau = 1 - T/Tc, kg/m^3; coefficients (Tc, rho_c, a, b, c, d, MW).
- ``DIPPR101``: mu = exp(A + B/T + C ln T + D T^E), Pa s.
- ``PPDS9``: mu = E exp(A X^(1/3) + B X^(4/3)), X = (C - T)/(T - D), Pa s.
- ``DIPPR100``: k = A + B T + C T^2 + D T^3 + E T^4, W/m/K.
- ``SATO_RIEDEL``: k = 1.1053 (3 + 20 (1 - Tr)^(2/3)) / (sqrt(MW)
  (3 + 20 (1 - Tbr)^(2/3))), coefficients (MW, Tc, Tb), W/m/K.

Each correlation carries the temperature range it is valid over. A concrete
temperature outside it raises :class:`LiquidRangeWarning`; the value is still
the correlation's, never clipped, so gradients stay smooth. (The one guard is
at the critical temperature in the forms that contain (1 - T/Tc)^n, where a
liquid no longer exists and the power would be NaN.)

Example:
    >>> from difflow.liquid_properties import liquid_density, liquid_viscosity
    >>> round(float(liquid_density("water", 298.15)), 1)
    997.0
    >>> mu = liquid_viscosity("water", 298.15)   # ~8.9e-4 Pa s
"""

from __future__ import annotations

import warnings
from collections.abc import Mapping
from typing import NamedTuple

import jax
import jax.numpy as jnp
import numpy as np
from jax import Array

from difflow._liquid_property_data import LIQUID_DATA, SOURCES

__all__ = [
    "LiquidCorrelation",
    "LiquidPropertyData",
    "LiquidRangeWarning",
    "get_liquid_properties",
    "list_liquid_species",
    "evaluate_correlation",
    "liquid_density",
    "liquid_molar_density",
    "liquid_viscosity",
    "liquid_thermal_conductivity",
    "liquid_property_source",
    "check_liquid_range",
    "mixture_liquid_molar_density",
    "mixture_liquid_density",
    "mixture_liquid_viscosity",
    "mixture_liquid_thermal_conductivity",
    "stream_liquid_properties",
]

#: Property keys and their names in messages.
PROPERTIES = {"rho": "density", "mu": "viscosity", "k": "thermal conductivity"}

# Smallest (1 - T/Tc) used in the critical-point guard.
_TAU_MIN = 1e-10


class LiquidRangeWarning(UserWarning):
    """A liquid property was evaluated outside its correlation's range."""


class LiquidCorrelation(NamedTuple):
    """One temperature correlation for a liquid property.

    Attributes:
        form: Equation form, one of the forms in the module docstring.
        coeffs: Coefficients, in the order the form lists them.
        Tmin: Lower end of the valid range (K).
        Tmax: Upper end of the valid range (K).
        range_stated: True if the source states this range; False if it was
            assumed (melting point to Tc for VDI-PPDS density and thermal
            conductivity; derived from the equation for PPDS9 viscosity; the
            method's usual range for an estimate).
        source: Key into the source citations; see
            :func:`liquid_property_source`.
    """

    form: str
    coeffs: tuple
    Tmin: float
    Tmax: float
    range_stated: bool
    source: str


class LiquidPropertyData(NamedTuple):
    """Liquid-property correlations for a pure species.

    Attributes:
        name: Species identifier (difflow database key).
        CAS: CAS registry number.
        MW: Molecular weight (g/mol), the database value.
        Tm: Melting point (K).
        rho: Density correlation.
        mu: Viscosity correlation.
        k: Thermal-conductivity correlation.
    """

    name: str
    CAS: str
    MW: float
    Tm: float
    rho: LiquidCorrelation
    mu: LiquidCorrelation
    k: LiquidCorrelation


def _correlation(d: dict) -> LiquidCorrelation:
    return LiquidCorrelation(d["form"], tuple(d["coeffs"]), d["Tmin"],
                             d["Tmax"], d["range_stated"], d["source"])


def list_liquid_species() -> list[str]:
    """Species with liquid-property data, sorted."""
    return sorted(LIQUID_DATA)


def get_liquid_properties(name: str) -> LiquidPropertyData:
    """Liquid-property correlations for a species (aliases accepted).

    Args:
        name: Species name or alias, as for ``get_species_data``.

    Returns:
        LiquidPropertyData.

    Raises:
        KeyError: If the species has no liquid-property data.

    Example:
        >>> get_liquid_properties("water").rho.source
        'vdi_ppds'
    """
    from difflow.database import _record_access, resolve_alias

    _record_access(name, "liquid")
    key = resolve_alias(name)
    if key not in LIQUID_DATA:
        raise KeyError(
            f"No liquid-property data for '{name}'. Available: "
            + ", ".join(list_liquid_species()))
    d = LIQUID_DATA[key]
    return LiquidPropertyData(
        name=key, CAS=d["CAS"], MW=d["MW"], Tm=d["Tm"],
        rho=_correlation(d["rho"]), mu=_correlation(d["mu"]),
        k=_correlation(d["k"]))


def _data(species: str | LiquidPropertyData) -> LiquidPropertyData:
    if isinstance(species, LiquidPropertyData):
        return species
    return get_liquid_properties(species)


def _tau(T: Array, Tc: float) -> Array:
    return jnp.maximum(1.0 - T / Tc, _TAU_MIN)


def evaluate_correlation(corr: LiquidCorrelation, T: Array | float) -> Array:
    """Evaluate a correlation in its native units, without range checks.

    Args:
        corr: The correlation.
        T: Temperature (K), scalar or array.

    Returns:
        mol/m^3 for density forms, Pa s for viscosity, W/m/K for thermal
        conductivity.
    """
    T = jnp.asarray(T, dtype=jnp.float64)
    p = corr.coeffs
    form = corr.form
    if form == "DIPPR105":
        A, B, C, D = p
        return A / B ** (1.0 + _tau(T, C) ** D)
    if form == "PPDS10":
        Tc, rhoc, a, b, c, d, MW = p
        tau = _tau(T, Tc)
        rho = (rhoc + a * tau**0.35 + b * tau ** (2.0 / 3.0) + c * tau
               + d * tau ** (4.0 / 3.0))
        return rho / MW * 1e3
    if form == "DIPPR101":
        A, B, C, D, E = p
        return jnp.exp(A + B / T + C * jnp.log(T) + D * T**E)
    if form == "PPDS9":
        A, B, C, D, E = p
        X = (C - T) / (T - D)
        X13 = jnp.cbrt(X)
        return E * jnp.exp(A * X13 + B * X * X13)
    if form == "DIPPR100":
        A, B, C, D, E = p
        return A + T * (B + T * (C + T * (D + T * E)))
    if form == "SATO_RIEDEL":
        MW, Tc, Tb = p
        num = 3.0 + 20.0 * _tau(T, Tc) ** (2.0 / 3.0)
        den = 3.0 + 20.0 * (1.0 - Tb / Tc) ** (2.0 / 3.0)
        return 1.1053 * num / (den * jnp.sqrt(MW))
    raise ValueError(f"unknown liquid correlation form {form!r}")


def check_liquid_range(species: str | LiquidPropertyData,
                       T: float) -> dict[str, dict]:
    """Report whether a temperature is inside each correlation's range.

    Args:
        species: Species name or LiquidPropertyData.
        T: Temperature (K), concrete.

    Returns:
        ``{prop: {'in_range', 'T_min', 'T_max', 'range_stated'}}`` for
        prop in ``'rho'``, ``'mu'``, ``'k'``.
    """
    data = _data(species)
    T = float(T)
    return {
        prop: {"in_range": c.Tmin <= T <= c.Tmax, "T_min": c.Tmin,
               "T_max": c.Tmax, "range_stated": c.range_stated}
        for prop, c in (("rho", data.rho), ("mu", data.mu), ("k", data.k))
    }


def _warn_out_of_range(data: LiquidPropertyData, prop: str, T) -> None:
    """Warn when a concrete T leaves the correlation's range (not under jit)."""
    if isinstance(T, jax.core.Tracer):
        return
    try:
        values = np.asarray(T, dtype=float)
    except Exception:
        return
    corr = getattr(data, prop)
    lo, hi = float(values.min()), float(values.max())
    if lo < corr.Tmin or hi > corr.Tmax:
        stated = "" if corr.range_stated else " (assumed range)"
        warnings.warn(
            f"{data.name} liquid {PROPERTIES[prop]} evaluated at "
            f"T = {lo:g}-{hi:g} K, outside {corr.Tmin:g}-{corr.Tmax:g} K"
            f"{stated} of its {corr.form} correlation; the value is an "
            "extrapolation.",
            LiquidRangeWarning, stacklevel=3)


def liquid_molar_density(species: str | LiquidPropertyData,
                         T: Array | float) -> Array:
    """Saturated-liquid molar density (mol/m^3).

    Args:
        species: Species name or LiquidPropertyData.
        T: Temperature (K).

    Returns:
        Molar density, mol/m^3.

    Example:
        >>> round(float(liquid_molar_density("water", 298.15)))
        55342
    """
    data = _data(species)
    _warn_out_of_range(data, "rho", T)
    return evaluate_correlation(data.rho, T)


def liquid_density(species: str | LiquidPropertyData,
                   T: Array | float) -> Array:
    """Saturated-liquid mass density (kg/m^3).

    Args:
        species: Species name or LiquidPropertyData.
        T: Temperature (K).

    Returns:
        Density, kg/m^3.

    Example:
        >>> round(float(liquid_density("ethanol", 298.15)), 1)  # measured 785.1
        786.0
    """
    data = _data(species)
    return liquid_molar_density(data, T) * data.MW * 1e-3


def liquid_viscosity(species: str | LiquidPropertyData,
                     T: Array | float) -> Array:
    """Liquid dynamic viscosity (Pa s).

    Args:
        species: Species name or LiquidPropertyData.
        T: Temperature (K).

    Returns:
        Viscosity, Pa s.

    Example:
        >>> 8.0e-4 < float(liquid_viscosity("water", 298.15)) < 9.5e-4
        True
    """
    data = _data(species)
    _warn_out_of_range(data, "mu", T)
    return evaluate_correlation(data.mu, T)


def liquid_thermal_conductivity(species: str | LiquidPropertyData,
                                T: Array | float) -> Array:
    """Liquid thermal conductivity (W/m/K).

    Args:
        species: Species name or LiquidPropertyData.
        T: Temperature (K).

    Returns:
        Thermal conductivity, W/m/K.

    Example:
        >>> 0.59 < float(liquid_thermal_conductivity("water", 298.15)) < 0.62
        True
    """
    data = _data(species)
    _warn_out_of_range(data, "k", T)
    return evaluate_correlation(data.k, T)


def liquid_property_source(species: str | LiquidPropertyData,
                           prop: str) -> str:
    """Citation for one of a species' liquid-property correlations.

    Args:
        species: Species name or LiquidPropertyData.
        prop: ``'rho'``, ``'mu'`` or ``'k'``.

    Returns:
        The citation string.
    """
    if prop not in PROPERTIES:
        raise ValueError(f"prop must be one of {list(PROPERTIES)}, got {prop!r}")
    return SOURCES[getattr(_data(species), prop).source]


# =============================================================================
# Mixtures
# =============================================================================


def _composition(mole_fractions: Mapping[str, Array | float]):
    names = list(mole_fractions)
    x = jnp.stack([jnp.asarray(mole_fractions[n], dtype=jnp.float64)
                   for n in names])
    x = x / jnp.sum(x, axis=0)
    data = [get_liquid_properties(n) for n in names]
    return data, x


def mixture_liquid_molar_density(mole_fractions: Mapping[str, Array | float],
                                 T: Array | float) -> Array:
    """Liquid-mixture molar density by ideal mixing of molar volumes (mol/m^3).

    1/rho_mix = sum_i x_i / rho_i. Excess volume is neglected; for
    water-alcohol mixtures that underestimates density by up to ~3%.

    Args:
        mole_fractions: ``{species: x_i}``; normalized here.
        T: Temperature (K).

    Returns:
        Molar density, mol/m^3.
    """
    data, x = _composition(mole_fractions)
    v = jnp.stack([1.0 / liquid_molar_density(d, T) for d in data])
    return 1.0 / jnp.sum(x * v, axis=0)


def mixture_liquid_density(mole_fractions: Mapping[str, Array | float],
                           T: Array | float) -> Array:
    """Liquid-mixture mass density (kg/m^3), ideal mixing of molar volumes.

    Args:
        mole_fractions: ``{species: x_i}``; normalized here.
        T: Temperature (K).

    Returns:
        Density, kg/m^3.
    """
    data, x = _composition(mole_fractions)
    MW = jnp.array([d.MW for d in data]).reshape((-1,) + (1,) * (x.ndim - 1))
    return (mixture_liquid_molar_density(mole_fractions, T)
            * jnp.sum(x * MW, axis=0) * 1e-3)


def mixture_liquid_viscosity(mole_fractions: Mapping[str, Array | float],
                             T: Array | float) -> Array:
    """Liquid-mixture viscosity by the log-linear rule (Pa s).

    ln mu_mix = sum_i x_i ln mu_i (Grunberg-Nissan with no interaction
    term). Good for similar nonpolar liquids; for aqueous or hydrogen-bonding
    mixtures the true viscosity can be well above this.

    Args:
        mole_fractions: ``{species: x_i}``; normalized here.
        T: Temperature (K).

    Returns:
        Viscosity, Pa s.
    """
    data, x = _composition(mole_fractions)
    ln_mu = jnp.stack([jnp.log(liquid_viscosity(d, T)) for d in data])
    return jnp.exp(jnp.sum(x * ln_mu, axis=0))


def mixture_liquid_thermal_conductivity(
        mole_fractions: Mapping[str, Array | float],
        T: Array | float) -> Array:
    """Liquid-mixture thermal conductivity by DIPPR procedure 9H (W/m/K).

    k_mix = (sum_i w_i / k_i^2)^(-1/2), with mass fractions w_i. DIPPR
    advises against it when the pure-component k differ by more than a
    factor of two, as in most aqueous mixtures.

    Args:
        mole_fractions: ``{species: x_i}``; normalized here.
        T: Temperature (K).

    Returns:
        Thermal conductivity, W/m/K.
    """
    data, x = _composition(mole_fractions)
    MW = jnp.array([d.MW for d in data]).reshape((-1,) + (1,) * (x.ndim - 1))
    w = x * MW / jnp.sum(x * MW, axis=0)
    k = jnp.stack([liquid_thermal_conductivity(d, T) for d in data])
    return jnp.sum(w / k**2, axis=0) ** -0.5


def stream_liquid_properties(stream: Mapping[str, Array]) -> dict[str, Array]:
    """Liquid properties of a stream at its temperature.

    Treats the whole stream as liquid; species with zero flow drop out of
    the mixing rules.

    Args:
        stream: A difflow stream (``F_<species>`` flows in mol/s and ``T``).

    Returns:
        ``{'rho', 'rho_molar', 'mu', 'k'}`` in kg/m^3, mol/m^3, Pa s and
        W/m/K, plus ``'Q'``, the volumetric flow (m^3/s).

    Example:
        >>> from difflow import make_stream
        >>> s = make_stream({"water": 10.0}, T=298.15, P=101325.0)
        >>> round(float(stream_liquid_properties(s)["Q"] * 1e6), 1)  # cm^3/s
        180.7
    """
    flows = {k[2:]: v for k, v in stream.items() if k.startswith("F_")}
    T = stream["T"]
    F = sum(flows.values())
    rho_molar = mixture_liquid_molar_density(flows, T)
    return {
        "rho": mixture_liquid_density(flows, T),
        "rho_molar": rho_molar,
        "mu": mixture_liquid_viscosity(flows, T),
        "k": mixture_liquid_thermal_conductivity(flows, T),
        "Q": F / rho_molar,
    }
